# Generated by Django 6.1 on 2026-09-14 14:31

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SD', 'Elementary School'), ('SMP', 'Junior High School'), ('SMA', 'Senior High School'), ('Kuliah', 'College')], default='full-time', max_length=10)),
                ('logo', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2026, 9, 14, 14, 31, 22, 543878, tzinfo=datetime.timezone.utc))),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 14, 14, 31, 22, 543617, tzinfo=datetime.timezone.utc)),
        ),
    ]
