# Generated by Django 6.1 on 2026-09-21 16:10

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_alter_education_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 21, 16, 10, 25, 679938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
