# Generated by Django 6.1 on 2026-09-27 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 27, 11, 21, 7, 402167, tzinfo=datetime.timezone.utc)),
        ),
    ]
