# Generated by Django 6.1 on 2026-09-28 06:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_education_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 28, 6, 0, 17, 882959, tzinfo=datetime.timezone.utc)),
        ),
    ]
