# Generated by Django 6.1 on 2026-09-28 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_education_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 28, 8, 2, 46, 323620, tzinfo=datetime.timezone.utc)),
        ),
    ]
